# Generated by Django 4.1.5 on 2023-01-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
                ('teacher', models.CharField(max_length=255, verbose_name='Учитель')),
                ('classroom', models.CharField(max_length=50, verbose_name='Аудитория')),
                ('started_at', models.DateTimeField(verbose_name='Дата/Время начала')),
                ('ended_at', models.DateTimeField(verbose_name='Дата/Время окончания')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
